# Prepare patient dataframe for Excel analysis
This notebook prepare the dataframe for the patients like the sexe distribution and age.
This notebook shouls be used for One Sleep analysis
Date: 25/08/2022

## Load data files

In [14]:
import pandas as pd

# %% Define constant
RAW_DATA_PATH = './data'
# load patient data frame
patient_df = pd.read_csv(RAW_DATA_PATH + "/patient.csv", sep=",")
# Load ONe-Sleep patient list
one_sleep_tracking_df = pd.read_csv(RAW_DATA_PATH + "/Tracking SMS OneSleep.csv", sep=",")
# Load Patient KPI
patient_kpi_df = pd.read_csv(RAW_DATA_PATH + "/patientKPI.csv", sep=",")
patient_kpi_df.head()

,Pat_Id_int,CompliancePriority,CurrentAverageCompliance28days_ft,CurrentAverageCompliance28days_tm,CurrentBillingForfait,CurrentBillingForfaitFrom,CurrentBillingForfaitTo,DataCompletness,IsNewPatient,LastCommunicationDate,...,TotalVisits,TotalWicallClinicalActions,CurrentAverageCompliance7days_ft,CurrentAverageCompliance7days_tm,EquipmentWirelessMain,Manufacturer,PatientUnreachable,LeaksMin,LeaksPercent,AHI
0,4480,0,6.95,06:57,SLEEP,30/01/2020,31/12/2999,28,0,22/08/2022,...,2,0,6.15,06:09,PPC AIRSENSE 10 AUTOSET,155,NaN,2,NaN,0.6
1,4553,0,6.91,06:54,SLEEP,26/02/2020,31/12/2999,44,0,15/08/2022,...,4,0,1.35,01:21,PPC AIRSENSE 10 AUTOSET,155,NaN,54,NaN,1.0
2,5930,0,5.93,05:55,SLEEP,25/02/2020,31/12/2999,28,0,22/08/2022,...,2,0,6.65,06:39,PPC AIRSENSE 10 AUTOSET,155,NaN,29,NaN,5.9
3,6058,10,5.57,05:34,SLEEP,30/01/2020,31/12/2999,28,0,22/08/2022,...,5,0,5.56,05:33,PPC AIRSENSE 10 AUTOSET,155,NaN,71,NaN,2.5
4,6719,0,6.17,06:10,SLEEP,25/02/2020,31/12/2999,28,0,22/08/2022,...,3,1,7.36,07:21,PPC AIRSENSE 10 AUTOSET,155,NaN,16,NaN,3.2

## Select only one patient in the overall patient data frame

In [11]:
patient_df['Pat_Id_int'] = patient_df['Pat_Id_int'].astype(int)
one_sleep_tracking_df['TRC_Ptt'] = one_sleep_tracking_df['TRC_Ptt'].astype(int)
one_sleep_patient_df = patient_df[patient_df['Pat_Id_int'].isin(one_sleep_tracking_df['TRC_Ptt'])]
one_sleep_patient_df

,Pat_Id_int,Pat_BU_str,Pat_Lastname_str,Pat_Firstname_str,Pat_Gender_str,Pat_BirthDate_dt,Pat_Phone_str,Pat_Phone2_str,Pat_Mail_str,Pat_IsActive_bl,Pat_WiComment_str,Pat_WiDisplayLeak_bl,Pat_TreatActiveNb_int,Pat_Unbilled_int,Pat_Unbilled_dt
0,4480,1,MANTEZOLO,Louise Kuntima,F,1962-12-29 00:00:00,06 68 36 97 53,04 78 86 09 31,loukunti3@gmail.com,1,Date :,NaN,1,NaN,NaN
1,4553,1,CARMONA,Francisca,F,1933-10-27 00:00:00,06 27 96 13 10,0478827394,francisca.carmona69@gmail.com,1,Date :,NaN,1,NaN,NaN
2,5930,1,VALOUR,Daniel,M,1941-06-17 00:00:00,06 63 26 26 17,0478461765,valour.daniel@neuf.fr,1,Date :,NaN,1,NaN,NaN
3,6058,1,MESSAGE,Pierre,M,1949-04-10 00:00:00,06 65 72 34 17,04 70 46 33 10,pierre.message@orange.fr,1,Date :,NaN,1,NaN,NaN
4,6719,1,GILLOT GIBAULT,Claude,M,1950-01-31 00:00:00,06 98 06 25 32,09 71 22 27 96,klodgg@orange.fr,1,Date :,NaN,1,NaN,NaN
5,7680,1,COLOMBAT,Dominique,M,1967-05-20 00:00:00,06 03 76 63 09,04 70 47 09 85,crisgrenouille@yahoo.fr,1,Date :,NaN,1,59.0,2021-11-30 00:00:00
6,7697,1,MARMIES,Etienne,M,1958-02-10 00:00:00,06 26 05 48 10,04 78 45 03 41,etienne_chantal@outlook.fr,1,Date :,NaN,1,NaN,NaN
7,13917,1,JAY,Marie France,F,1940-09-03 00:00:00,0684493131,04 78 56 00 38,marie-france.gay69@orange.fr,1,Date :,NaN,1,18.0,2022-07-31 00:00:00
8,26632,1,BARBET,Bernard,M,1949-07-08 00:00:00,06 14 06 00 30,06 37 04 70 92,garoju38@gmail.com,1,Date :,NaN,1,NaN,NaN
9,28205,1,DUBLASSY,Thierry,M,1965-09-18 00:00:00,06 84 48 56 37,04 81 18 06 26,thierrydublassy@gmail.com,1,Date :,NaN,1,NaN,NaN
10,34718,1,CHATELET,Stephane,M,1973-10-05 00:00:00,06 27 79 53 35,NT,stephane.chatelet@wanadoo.fr,1,12/07/21=a toujours eu des nuits entrecoupées ...,NaN,1,5.0,2022-07-31 00:00:00
11,35703,1,GATIER,Pascal,M,1963-04-11 00:00:00,06 19 41 81 37,04 70 28 63 89,nounet.66140@gmail.com,1,Date :,NaN,1,NaN,NaN
12,37340,1,JAULIN,Germaine,F,1957-04-15 00:00:00,0620076730,04 78 49 36 75,noreply@linde.com,1,Date :,NaN,1,NaN,NaN
13,41742,1,VILAR,Pierre,M,1945-01-17 00:00:00,0681270246,0478497137,piepierre69@gmail.com,1,03/03/2021=ptt barbu +++fuites connues et non ...,NaN,1,NaN,NaN
14,42149,1,BRUNET,Nicolas,M,1961-05-08 00:00:00,06 30 92 13 95,06 31 54 09 91,nicolas.brunet2000@gmail.com,1,Date :,NaN,1,NaN,NaN
15,44359,1,CHIERA,Bruno,M,1961-03-08 00:00:00,06 64 68 22 66,06 56 86 69 41,ttb.chiera@hotmail.com,1,19/11/20=se couche tard et dort moins bien en ...,NaN,1,41.0,2022-06-30 00:00:00
16,49144,1,DUSSAUSSOY,Magalie,F,1973-11-05 00:00:00,06 49 27 16 06,0649271606,fakad03@yahoo.fr,1,Date :,NaN,1,NaN,NaN
17,66855,1,PALUMBO,Lionel,M,1994-09-02 00:00:00,0783306514,06 86 97 65 59,palumbo94@hotmail.fr,1,Date :,NaN,1,NaN,NaN
18,67249,1,DA SILVA CEBOLA,Vitor,M,1974-01-01 00:00:00,06 62 71 85 45,NaN,vitorcebola@hotmail.com,1,08/03/22 : part du 15/03/2022 pour environ 1 m...,NaN,1,NaN,NaN
19,79682,1,MARTINEZ,Jean Paul,M,1958-10-05 00:00:00,06 80 71 97 73,06 80 71 97 73,ulysse.0@hotmail.fr,1,22/03/21=ptt dort sur le dos+04/05/21=KC de l'...,NaN,1,5.0,2022-07-31 00:00:00

## Select only KPIs for the ONe-Sleep patients

In [15]:
patient_kpi_df['Pat_Id_int'] = patient_kpi_df['Pat_Id_int'].astype(int)
patient_kpi_df = patient_kpi_df[patient_kpi_df['Pat_Id_int'].isin(one_sleep_tracking_df['TRC_Ptt'])]
patient_kpi_df.head()

,Pat_Id_int,CompliancePriority,CurrentAverageCompliance28days_ft,CurrentAverageCompliance28days_tm,CurrentBillingForfait,CurrentBillingForfaitFrom,CurrentBillingForfaitTo,DataCompletness,IsNewPatient,LastCommunicationDate,...,TotalVisits,TotalWicallClinicalActions,CurrentAverageCompliance7days_ft,CurrentAverageCompliance7days_tm,EquipmentWirelessMain,Manufacturer,PatientUnreachable,LeaksMin,LeaksPercent,AHI
0,4480,0,6.95,06:57,SLEEP,30/01/2020,31/12/2999,28,0,22/08/2022,...,2,0,6.15,06:09,PPC AIRSENSE 10 AUTOSET,155,NaN,2,NaN,0.6
1,4553,0,6.91,06:54,SLEEP,26/02/2020,31/12/2999,44,0,15/08/2022,...,4,0,1.35,01:21,PPC AIRSENSE 10 AUTOSET,155,NaN,54,NaN,1.0
2,5930,0,5.93,05:55,SLEEP,25/02/2020,31/12/2999,28,0,22/08/2022,...,2,0,6.65,06:39,PPC AIRSENSE 10 AUTOSET,155,NaN,29,NaN,5.9
3,6058,10,5.57,05:34,SLEEP,30/01/2020,31/12/2999,28,0,22/08/2022,...,5,0,5.56,05:33,PPC AIRSENSE 10 AUTOSET,155,NaN,71,NaN,2.5
4,6719,0,6.17,06:10,SLEEP,25/02/2020,31/12/2999,28,0,22/08/2022,...,3,1,7.36,07:21,PPC AIRSENSE 10 AUTOSET,155,NaN,16,NaN,3.2

## Save dataframes

In [18]:
PROCESS_DATA_PATH = './data/process'
patient_kpi_df.to_csv(PROCESS_DATA_PATH + '/patient_kpi.csv') 
one_sleep_patient_df.to_csv(PROCESS_DATA_PATH + '/one_sleep_patient.csv')